version: "3.8"

### Uses a network within Docker to allow Pi-Hole and Unbound to communicate.
### Unbound is not accessible from anywhere except Pi-Hole
### Consider docker-compose.yml.alternative if you want to use Pi-Hole for DHCP

services:
  pihole:
    depends_on:
      - unbound
    container_name: pihole
    image: pihole/pihole:latest
    ### For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ### (This is what docker-compose.yml.alternative is for)
    ports:
      - "53:53"
      - "53:53/udp"
      - "80:80"
      - "443:443"
    ### Only needed for DHCP
    #  - "67:67/udp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: ${WEB_PASS}
    ### Required for DHCP
    #  ServerIP: ${HOST_IP}
      PIHOLE_DNS_: '172.30.0.2'
    volumes:
      - './etc-pihole:/etc/pihole'
    ### Required for DHCP
    ### https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    restart: unless-stopped
    dns:
      - '172.30.0.2'
    networks:
      internal:
        ipv4_address: 172.30.0.3
  unbound:
    container_name: unbound
    image: bdagenais/unbound:latest
    restart: unless-stopped
    networks:
      internal:
        ipv4_address: 172.30.0.2
networks:
  internal:
    driver: bridge
    ipam:
     config:
       - subnet: 172.30.0.0/16
         gateway: 172.30.0.1
